version: '3.9'
services:
  web:
    build: .
    container_name: bot-flask
    environment:
      - FLASK_APP=main.py:init_app()
#      - FLASK_APP=app.py
#
      - USERNAME=test
      - PASSWORD=12345
      - BD_HOST=pg-project2
    ports:
      - '5000:5000'
    networks:
      - app-network

  db:
    image: postgres
    container_name: pg-project2
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: contact_book
    networks:
      - app-network
    ports:
      - '5432:5432'

networks:
  app-network:
    driver: bridge